package com.controller;

import java.util.List;
import java.util.Random;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class ReviewController {

	

    private final List<String> reviews = List.of(
    		"Great furniture quality and excellent customer service.",
    		"The rental process was quick and completely hassle-free.",
    		"Really happy with the furniture condition and timely delivery.",
    		"Affordable prices with premium-looking furniture.",
    		"The team was friendly and handled everything professionally.",
    		"Furniture arrived clean, stylish, and ready to use.",
    		"Very smooth experience from booking to installation.",
    		"Highly satisfied with the quality of the rented furniture.",
    		"The delivery team was punctual and very helpful.",
    		"Excellent service with flexible rental options.",
    		"The furniture looked exactly like the pictures online.",
    		"Good quality products at reasonable rental prices.",
    		"The entire process was simple and well organized.",
    		"Customer support was responsive and very cooperative.",
    		"Furniture was comfortable and beautifully maintained.",
    		"A great option for anyone looking to rent furniture.",
    		"The installation was completed quickly and professionally.",
    		"Very impressed with the overall service experience.",
    		"The furniture added a modern look to my home.",
    		"Everything was delivered exactly on the promised date.",
    		"The rental plans are budget-friendly and convenient.",
    		"Reliable service with excellent product quality.",
    		"The sofa was extremely comfortable and looked premium.",
    		"Happy with both the service and the furniture quality.",
    		"The furniture was clean, sturdy, and well maintained.",
    		"Professional staff and smooth booking experience.",
    		"Delivery and setup were completed without any delays.",
    		"Great collection of furniture for every home.",
    		"The products were in excellent condition upon delivery.",
    		"Easy booking process with transparent pricing.",
    		"The furniture exceeded my expectations.",
    		"Everything was handled efficiently from start to finish.",
    		"The rental service saved me both time and money.",
    		"Very convenient solution for a fully furnished home.",
    		"The quality of the furniture was outstanding.",
    		"Support team was polite and always ready to help.",
    		"Quick installation and excellent customer care.",
    		"The furniture looked elegant and felt comfortable.",
    		"Highly recommend this rental service to others.",
    		"Everything arrived safely and in perfect condition.",
    		"Very professional service with quality furniture.",
    		"The experience was smooth and stress-free.",
    		"Great value for money with flexible plans.",
    		"The products were delivered neatly and on time.",
    		"Furniture quality was better than expected.",
    		"Excellent rental service with friendly staff.",
    		"The wardrobe was spacious and looked brand new.",
    		"The mattress was clean and very comfortable.",
    		"Everything matched the description perfectly.",
    		"Fast delivery and reliable customer support.",
    		"The furniture transformed my apartment beautifully.",
    		"The entire rental process was very convenient.",
    		"Great experience with prompt delivery.",
    		"The quality remained excellent throughout the rental period.",
    		"Booking furniture has never been this easy.",
    		"The products were stylish and durable.",
    		"Excellent communication from the support team.",
    		"Very pleased with the overall experience.",
    		"Professional installation and quality furniture.",
    		"Everything was managed smoothly without any issues.",
    		"The rental plans suited my budget perfectly.",
    		"The furniture was modern and well designed.",
    		"Great customer service from beginning to end.",
    		"The delivery executives were polite and efficient.",
    		"The furniture fit perfectly in my apartment.",
    		"Very satisfied with the quality and cleanliness.",
    		"Affordable rental service with premium products.",
    		"The entire experience was pleasant and convenient.",
    		"Furniture arrived in excellent condition.",
    		"Everything was completed exactly as promised.",
    		"The furniture looked fresh and well maintained.",
    		"Very reliable furniture rental company.",
    		"The booking process was fast and easy.",
    		"Excellent furniture collection to choose from.",
    		"The team made the whole experience effortless.",
    		"Very comfortable furniture with attractive designs.",
    		"Happy with the affordable rental packages.",
    		"The furniture quality was truly impressive.",
    		"Everything was delivered without any damage.",
    		"The service was quick and highly professional.",
    		"Very good experience with the rental process.",
    		"The products looked almost brand new.",
    		"The support team resolved my queries quickly.",
    		"Great rental service with transparent pricing.",
    		"The furniture was stylish and comfortable.",
    		"Highly impressed by the professionalism of the staff.",
    		"Delivery and installation were completed perfectly.",
    		"The furniture made my home feel complete.",
    		"Very happy with the smooth rental experience.",
    		"The products were clean and hygienic.",
    		"The rental process was straightforward and simple.",
    		"Excellent experience from start to finish.",
    		"Quality furniture at affordable monthly rent.",
    		"The team ensured everything was installed properly.",
    		"Very dependable service with quality products.",
    		"The furniture was durable and comfortable.",
    		"Booking was easy and the service was excellent.",
    		"Everything arrived on time without any hassle.",
    		"The overall experience exceeded my expectations.",
    		"Professional service with outstanding furniture quality.",
    		"The products looked elegant in my living space.",
    		"Really satisfied with the service and support.",
    		"One of the best furniture rental experiences I've had."

    );

    @GetMapping("/api/review")
    public String getRandomReview() {
        Random random = new Random();
        return reviews.get(random.nextInt(reviews.size()));
    }
}
